#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InputView.Resource", IsApplication=true)]

namespace InputView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int controller = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dpad_down = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dpad_left = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dpad_right = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dpad_up = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int l_stick = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int lb = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int lt = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int menu = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int o = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int r_stick = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int rb = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int rt = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int thumbl = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int thumbr = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int u = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int y = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
