/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef        int(*OuyaPlugin_getAxis_t)(int deviceId, int axis);
typedef       bool(*OuyaPlugin_isPressed_t)(int deviceId, int keyCode);
typedef       bool(*OuyaPlugin_isPressedDown_t)(int deviceId, int keyCode);
typedef       bool(*OuyaPlugin_isPressedUp_t)(int deviceId, int keyCode);
typedef       void(*OuyaPlugin_clearButtonStates_t)();
typedef const char*(*OuyaPlugin_getDeviceName_t)(int playerNum);
typedef       void(*OuyaPlugin_initOuyaPlugin_t)(const char* jsonData, s3eCallback onSuccess, s3eCallback onFailure);
typedef       void(*OuyaPlugin_asyncOuyaRequestGamerInfo_t)(s3eCallback onSuccess, s3eCallback onFailure, s3eCallback onCancel);
typedef       void(*OuyaPlugin_asyncOuyaRequestProducts_t)(const char* productsJson, s3eCallback onSuccess, s3eCallback onFailure, s3eCallback onCancel);
typedef       void(*OuyaPlugin_asyncOuyaRequestPurchase_t)(const char* purchasable, s3eCallback onSuccess, s3eCallback onFailure, s3eCallback onCancel);
typedef       void(*OuyaPlugin_asyncOuyaRequestReceipts_t)(s3eCallback onSuccess, s3eCallback onFailure, s3eCallback onCancel);
typedef        int(*OuyaPlugin_JSONObject_Construct_t)();
typedef       void(*OuyaPlugin_JSONObject_Put_t)(int jsonObject, const char* name, const char* value);
typedef const char*(*OuyaPlugin_JSONObject_ToString_t)(int jsonObject);
typedef        int(*OuyaPlugin_JSONArray_Construct_t)();
typedef       void(*OuyaPlugin_JSONArray_Put_t)(int jsonArray, int index, int jsonObject);
typedef const char*(*OuyaPlugin_JSONArray_ToString_t)(int jsonArray);

/**
 * struct that gets filled in by ODKRegister
 */
typedef struct ODKFuncs
{
    OuyaPlugin_getAxis_t m_OuyaPlugin_getAxis;
    OuyaPlugin_isPressed_t m_OuyaPlugin_isPressed;
    OuyaPlugin_isPressedDown_t m_OuyaPlugin_isPressedDown;
    OuyaPlugin_isPressedUp_t m_OuyaPlugin_isPressedUp;
    OuyaPlugin_clearButtonStates_t m_OuyaPlugin_clearButtonStates;
    OuyaPlugin_getDeviceName_t m_OuyaPlugin_getDeviceName;
    OuyaPlugin_initOuyaPlugin_t m_OuyaPlugin_initOuyaPlugin;
    OuyaPlugin_asyncOuyaRequestGamerInfo_t m_OuyaPlugin_asyncOuyaRequestGamerInfo;
    OuyaPlugin_asyncOuyaRequestProducts_t m_OuyaPlugin_asyncOuyaRequestProducts;
    OuyaPlugin_asyncOuyaRequestPurchase_t m_OuyaPlugin_asyncOuyaRequestPurchase;
    OuyaPlugin_asyncOuyaRequestReceipts_t m_OuyaPlugin_asyncOuyaRequestReceipts;
    OuyaPlugin_JSONObject_Construct_t m_OuyaPlugin_JSONObject_Construct;
    OuyaPlugin_JSONObject_Put_t m_OuyaPlugin_JSONObject_Put;
    OuyaPlugin_JSONObject_ToString_t m_OuyaPlugin_JSONObject_ToString;
    OuyaPlugin_JSONArray_Construct_t m_OuyaPlugin_JSONArray_Construct;
    OuyaPlugin_JSONArray_Put_t m_OuyaPlugin_JSONArray_Put;
    OuyaPlugin_JSONArray_ToString_t m_OuyaPlugin_JSONArray_ToString;
} ODKFuncs;
