/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef ODK_AUTODEFS_H
#define ODK_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ODK_NAME "ODK"
#define S3E_EXT_ODK_HASH 0xb889863

#endif /* !ODK_AUTODEFS_H */
